### PR TITLE
New snippet to assert URL ends with a specified string

### PR DESCRIPTION
**Pull request by bertold**
Implemented a snippet that verifies that the current page URL ends with the value of the variable stored in endsWith.

### CODE REVIEW

**Comment by EdgarJoelM** [comment]
Correct me if I am wrong, but I think the functionality of this snippet is the same as https://github.com/mablhq/mabl-JavaScript-snippets/blob/master/mabl%20snippets/assertPath.js

Should this be a replacement to the prior? Or does it result in the same functionality.

**Comment by bertold** [comment]
I could go either way: either update assertPath so that the ending string is not hard-wired inside the snippet. Here the point is that I would like to pass in a parameter to the step and reuse this step.

**Review by srvance — COMMENTED** [review]
Want to take a stab at adding it as an official feature, instead?

**Comment by bertold** [comment]
@srvance - yes, I would love to. I will close this pull request.

**Pull request closed without merging**
